create boxes controller
Akki-on-Rails/boxtag pull request #12
Opened 2022-08-13 15:39 UTC by menakadevisundaramoorthy

add new and create

2022-08-13 15:41 UTC, Jordan-Patel reviewed
@box.user = current_user will cause an error as the user is associated with the UserCollection, not the box so no need for this line.

2022-08-13 15:41 UTC, Akki-on-Rails commented on app/controllers/boxes_controller.rb
> +      redirect_to booking_path(@box)
here your path is wrong (booking)

2022-08-13 15:43 UTC, Akki-on-Rails requested changes
wrong path for create method

2022-08-16 17:08 UTC, Akki-on-Rails approved these changes

2022-08-16 17:08 UTC, Jordan-Patel approved these changes
Looks good.

2022-08-16 17:18 UTC, merged